import React, { Component } from 'react';
 import {Table} from 'react-bootstrap';
class Share_Vehicle_Table extends Component {
    render() {
        console.log("Received shareObj");
    console.log(this.props.shareObj);
        return (
<Table responsive>
  <thead>
    <tr>
      <th>Name</th>
      <th>CarType</th>
      <th>StartTime</th>
      <th>ReturnTime</th>
      <th>Origin</th>
      <th>Destination</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Rahul</td>
      <td>Rider</td>
      <td>7</td>
      <td>7</td>
      <td>Panchkula</td>
      <td>Chitkara</td>
    </tr>
    <tr>
      <td>Pankaj</td>
      <td>Provider</td>
      <td>7</td>
      <td>5</td>
      <td>Baddi</td>
      <td>Chitkara</td>
    </tr>
    <tr>
      <td>Ankit</td>
      <td>Provider</td>
      <td>9</td>
      <td>5</td>
      <td>Baddi</td>
      <td>Chitkara</td>
    </tr>
    <tr>
      <td>Sarbeshwar</td>
      <td>Rider</td>
      <td>6</td>
      <td>6</td>
      <td>Kharar</td>
      <td>Chitkara</td>
    </tr>
    <tr>
      <td>Sarthak</td>
      <td>Provider</td>
      <td>8</td>
      <td>5</td>
      <td>Baddi</td>
      <td>Chitkara</td>
    </tr>
    <tr>
      <td>MOH101</td>
      <td>Provider</td>
      <td>5</td>
      <td>7</td>
      <td>Chitkara</td>
      <td>Kharar</td>
    </tr>
    <tr>
      <td>CH25</td>
      <td>Provider</td>
      <td>5</td>
      <td>6</td>
      <td>Chitkara</td>
      <td>Chandigarh</td>
    </tr>
    <tr>
      <td>CH99</td>
      <td>Provider</td>
      <td>5</td>
      <td>6</td>
      <td>Chitkara</td>
      <td>Zirakpur</td>
    </tr>
    <tr>
      <td>MOH202</td>
      <td>Provider</td>
      <td>5</td>
      <td>6</td>
      <td>Chitkara</td>
      <td>Mohali</td>
    </tr>
    <tr>
      <td>CH55</td>
      <td>Provider</td>
      <td>5</td>
      <td>7</td>
      <td>Chitkara</td>
      <td>Baddi</td>
    </tr>
  </tbody>
</Table>
        );
    }
}

export default Share_Vehicle_Table;